name: CI C Coverage

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          apt update
          apt install -y tzdata
          dpkg-reconfigure -f noninteractive tzdata
          apt install -y build-essential check lcov gcovr make git curl

      - name: Compile project
        run: make

      - name: Run unit tests
        run: make test

      - name: Generate coverage
        run: |
          make coverage
          make gcovr-html

      - name: Upload to Codecov manually
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage.info -F unittests
          
